name: "Security checks"
on:
    pull_request:
        branches:
            - master

jobs:
    security-tests-part-1:
        name: "API Security tests - part 1"
        timeout-minutes: 30
        runs-on: ubuntu-latest
        steps:
            - name: Install node
              uses: actions/setup-node@v2
              with:
                  node-version: "20.0.0"

            - name: Install yarn
              run: npm install -g yarn

            - name: Checkout repo
              uses: actions/checkout@main
              with:
                  submodules: "true"

            - name: Install other dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get -y install hwloc jq pkg-config bzr ocl-icd-opencl-dev
                  sudo apt install zsh -y
                  yarn install

            - name: Install mythril
              run: pip3 install mythril

            - name: Run checks on Account API
              run: make security_account_api

            - name: Run checks on Market API
              run: make security_market_api

            - name: Run checks on Miner API
              run: make security_miner_api

            - name: Run checks on VerifReg API
              run: make security_verifreg_api

    security-tests-part-2:
        name: "API Security tests - part 2"
        timeout-minutes: 30
        runs-on: ubuntu-latest
        steps:
            - name: Install node
              uses: actions/setup-node@v2
              with:
                  node-version: "20.0.0"

            - name: Install yarn
              run: npm install -g yarn

            - name: Checkout repo
              uses: actions/checkout@main
              with:
                  submodules: "true"

            - name: Install other dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get -y install hwloc jq pkg-config bzr ocl-icd-opencl-dev
                  sudo apt install zsh -y
                  yarn install

            - name: Install mythril
              run: pip3 install mythril

            - name: Run checks on Power API
              run: make security_power_api

            - name: Run checks on Datacap API
              run: make security_datacap_api

            - name: Run checks on Send API
              run: make security_send_api

            - name: Run checks on Precompiles API
              run: make security_precompiles_api
